### ISSUE TITLE
Is this package maintained?

### ISSUE THREAD

**Issue by jenstroeger** [henribru/googleapis-common-protos-stubs#6]

**Comment by henribru** [comment]
Sorry for the late reply, didn't notice this issue. I don't maintain it very actively as I mainly just use it to support https://github.com/henribru/google-ads-stubs and that hasn't required it to be very up-to-date. I just released a new version that adds support for v1.56.4 though. I've also loosened the version requirements, which should make it easier to continue using it even if there's a long time between releases.
